---
all:
  children:
    production:
      hosts:
        prod-server-1:
          ansible_host: "{{ lookup('env', 'PROD_SERVER_IP') | default('127.0.0.1') }}"
          ansible_user: "{{ lookup('env', 'ANSIBLE_USER') | default('ubuntu', true) }}"
          ansible_ssh_private_key_file: "{{ lookup('env', 'SSH_KEY_PATH') | default('~/.ssh/id_rsa') }}"
    staging:
      hosts:
        staging-server-1:
          ansible_host: "{{ lookup('env', 'STAGING_SERVER_IP') | default('127.0.0.1') }}"
          ansible_user: "{{ lookup('env', 'ANSIBLE_USER') | default('ubuntu', true) }}"
          ansible_ssh_private_key_file: "{{ lookup('env', 'SSH_KEY_PATH') | default('~/.ssh/id_rsa') }}"
    docker_hosts:
      children:
        production:
        staging:
